### ISSUE TITLE
Multi-level factors and continuous covariates

### ISSUE THREAD

**Issue by PauBadiaM** [owkin/PyDESeq2#100]
Hi devs,

Amazing work! It's really nice to have such a strong DEA framework finally available in python. Here's a suggestion regarding factors:

**Is your feature request related to a problem? Please describe.**
Currently pydeseq2 is limited to bi-level factors, limiting its usage whenever there are multi-level factors or continuous covariates.

**Describe the solution you'd like**
I know it might be cumbersome to implement, but it would be convenient to add support to multi-level factors and continuous covariates in the `design_factors` argument of DeseqDataSet.

**Describe alternatives you've considered**
For multi-level factors, the current alternative is to generate a single `DeseqDataSet` for each combination of groups, making it tedious to deal with (although it's true that depending on the within-group variability differences it might be needed as explained in the [original docs](https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#if-i-have-multiple-groups-should-i-run-all-together-or-split-into-pairs-of-groups)).

For continuous covariates, the current alternative is to cut them into bins and generate factors of them, which results in a multi-level factor with the previously mentioned problems.

**Comment by BorisMuzellec** [comment]
Hi @PauBadiaM, thanks for your interest in PyDESeq2!

I'm currently working on multi-level designs (see PR #101), hopefully they should be supported in a couple of days.

Unfortunately, we probably won't have the bandwidth to work on continuous variables in the near future, but we'd be glad to review a PR should someone want to implement continuous covariates :) !

**Comment by laserson** [comment]
+1 for continuous covariates!

**Comment by mbernste** [comment]
Really great work. 

+1 for continuous covariates. At a high level, what changes/refactoring would be needed to support this?

**Comment by mikecuoco** [comment]
+1 for continuous covariates! So useful for most experimental designs

**Comment by njbernstein** [comment]
+ 1 for continuous covariates

**Comment by myz540** [comment]
+1 for continuous covariates
