### ISSUE TITLE
ENH quiet mode

### ISSUE THREAD

**Issue by BorisMuzellec** [owkin/PyDESeq2#102]
**Is your feature request related to a problem? Please describe.**
The `DeseqDataSet` and `DeseqStats` classes print a message at each step of the pipeline (e.g. fitting size factors, or dispersions), including when those steps are nested within another task (e.g., computing VST #99), which can lead to many useless statements being printed.

**Describe the solution you'd like**
Having a verbosity parameter that would allow controlling the desired level of verbosity of `fit_size_factors`, `fit_genewise_dispersions`, `fit_dispersion_trend`, and so on.  

**Describe alternatives you've considered**
Deactivating print statements from nested calls (e.g. VST).

**Additional context**
Currently, computing VST (#99) prints the following:
![Capture d’écran 2023-03-22 à 09 59 40](https://user-images.githubusercontent.com/11092154/226852219-7508d1a8-7040-44de-8b17-9b9f85a0c308.png)

**Comment by dbdimitrov** [comment]
Hi,

Indeed, verbosity would be fantastic to have.
It might be also worthwhile to use the same quiet flag for the `display` calls.

In the meantime, `%%capture` seems to the the trick for me.
https://stackoverflow.com/questions/23692950/how-do-you-suppress-output-in-jupyter-running-ipython

**Comment by BorisMuzellec** [comment]
Fixed in #146
