### ISSUE TITLE
`fit_alpha_mle` questions

### ISSUE THREAD

**Issue by mikelove** [owkin/PyDESeq2#106]
in the `loss` and `dloss` functions, why not just use `log_alpha` here:

https://github.com/owkin/PyDESeq2/blob/main/pydeseq2/utils.py#L612

and here:

https://github.com/owkin/PyDESeq2/blob/main/pydeseq2/utils.py#L633

You can likewise just define `log_alpha_hat` once to avoid recomputing it on every function and gradient evaluation.

And since this is optimizing in the log space, I wouldn't put an `alpha` in the denominator (we just differentiate wrt `log_alpha`). Instead of:

`reg_grad += (log_alpha - log_alpha_hat) / (alpha * prior_disp_var)`

I would have:

`reg_grad += (log_alpha - log_alpha_hat) / prior_disp_var`

I'm not sure if this is why, but I see a lack of shrinkage sometimes for high counts (where we do shrink these in DESeq2), and I'm trying to figure out the source. Have you seen this?

<img width="569" alt="Screenshot 2023-03-28 at 6 56 51 PM" src="https://user-images.githubusercontent.com/69203/228385234-7fdccb68-59e5-49a0-81e4-4f61e8e7303c.png">

**Comment by BorisMuzellec** [comment]
Hi, indeed there are some inconsistencies in the optimization. It was designed to optimize w.r.t. `log(alpha)` but the derivative was computed w.r.t. `alpha`. I opened a PR (#107) to fix this.

You're absolutely right about unnecessary recomputation of `log(alpha)` and `log(alpha_hat)`. Computation of `W` could also be avoided when CR regularization is not applied.

Do you have a link to some code (or a piece of code) to reproduce the figure above, so I can see whether it fixes the issue?

Thanks again for your help in improving the code!

**Comment by mikelove** [comment]
This appears to be fixed via #107 

![Screenshot 2023-03-30 at 11 36 10 AM](https://user-images.githubusercontent.com/69203/228889482-23f1c504-f230-4221-9b43-0362734331fa.png)
