### ISSUE TITLE
[BUG] AttributeError: module 'numpy' has no attribute 'MachAr'

### ISSUE THREAD

**Issue by PABannier** [owkin/PyDESeq2#112]
**Describe the bug**
When trying to import `from pydeseq2.dds import DeseqDataSet`, the following error is thrown:
`AttributeError: module 'numpy' has no attribute 'MachAr'`.

**To Reproduce**
Create a new Conda environment and install PyDeSeq2.

**Expected behavior**
I can import `DeseqDatqset` correctly.

**Additional context**
The problem is [known](https://stackoverflow.com/questions/75371176/module-numpy-has-no-attribute-machar). My env has `Numpy == 1.24.2`. Looking at your requirements, you only specify a lower bound on the version of Numpy `>=1.23.0`. It turns out this error is linked to statsmodels. Switching to `numpy==1.23.0` did the trick for me.

**Comment by BorisMuzellec** [comment]
Hi @PABannier, thanks for this feedback.

I am unable to reproduce the issue in a fresh conda environment. Here's what I tried:

```
conda create -n pydeseq2
conda activate pydeseq2
conda install pip
pip install pydeseq2
```

From there, `from pydeseq2.dds import DeseqDataSet` executes bug-free.

Could you provide some additional detail on your python and package versions? 

In the above setup, I have `python 3.11.2`, `numpy 1.24.2` and `statsmodels 0.13.5`.
