### ISSUE TITLE
Implement fitType="mean" for vst

### ISSUE THREAD

**Issue by scottgigante-immunai** [owkin/PyDESeq2#116]
DESeq2 has a fit type "mean" for the vst which is used as the fallback when the parametric fit fails. It would be nice to have an equivalent in the python implementation.

Here's my attempt based on https://github.com/mikelove/DESeq2/blob/devel/R/vst.R#L188 and https://github.com/mikelove/DESeq2/blob/devel/R/core.R#L892

```
        gene_dispersions = self.varm["genewise_dispersions"]
        use_for_mean = gene_dispersions > 10*self.min_disp
        mean_disp = scipy.stats.trim_mean(gene_dispersions[use_for_mean], proportiontocut=0.001)
        self.layers["vst_counts"] = ( 2 * np.arcsinh(np.sqrt(mean_disp * self.layers["normed_counts"])) - np.log(mean_disp) - np.log(4) ) / np.log(2)
```

**Comment by BorisMuzellec** [comment]
Hi @scottgigante-immunai, do you feel like opening a PR? 

I'd be happy to add this feature once we check that the results match those of DESeq2 (this I can do, once the PR is open I'll add a unit test based on this repo's synthetic data).

Thanks!
