### ISSUE TITLE
[BUG] deseq2_norm throws KeyError when called on a pandas DataFrame

### ISSUE THREAD

**Issue by epolanco03** [owkin/PyDESeq2#122]
**Describe the bug**
We are trying to use deseq2_norm to normalized your example data set and our own rna_seq experiment, in both cases the function does not work.

**To Reproduce**
python version = 3.11.3
code : 
counts_df = load_example_data(
    modality="raw_counts",
    dataset="synthetic",
    debug=False,
)

deseq2_norm(counts_df)

**Expected behavior**
We were expecting to get a dataframe with the normalized values of the gens in each sample.

**Screenshots**
![image](https://user-images.githubusercontent.com/130982623/235124582-72cd6a37-df72-43e0-8ce4-e7baf53f6679.png)
![image](https://user-images.githubusercontent.com/130982623/235124836-3c2f6e54-45e2-41ee-a170-9243dc0d45b2.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 22.04

**Additional context**

**Comment by BorisMuzellec** [comment]
Hi @epolanco03, thanks for reporting this bug.

I've been able to reproduce it, I'll try to fix it ASAP. This could be related to changes introduced by `pandas` version 2.0.

In the meantime, getting size factors using a DeseqDataSet seems to be working, e.g.,

```
from pydeseq2.utils import load_example_data
from pydeseq2.dds import DeseqDataSet

counts_df = load_example_data(modality="raw_counts")
clinical_df = load_example_data(modality="clinical")

dds = DeseqDataSet(counts=counts_df, clinical=clinical_df)
dds.fit_size_factors()

dds.obsm["size_factors"]
```
