### ISSUE TITLE
Single cell implimentaion of PyDESeq2

### ISSUE THREAD

**Issue by kvshams** [owkin/PyDESeq2#13]
Great work!.
Any plans for making a single cell implementation similar to the one`seurat` implementation of DESeq2 for single cell.
Thanks,
Shams

**Comment by BorisMuzellec** [comment]
Hi Shams, thanks for your interest in our work!
Right now we don't have plans to implement single cell pipelines, we still have a lot to do with bulk RNAseq :).
Besides, there are already nice packages for scRNA-seq in python: check out [Scanpy](https://scanpy.readthedocs.io/en/stable/)
