### ISSUE TITLE
Nan in Padj even after turning off independent filter

### ISSUE THREAD

**Issue by jairaj-mathur** [owkin/PyDESeq2#148]
**Describe the bug**
I am getting NaN p_value and p_adj values even after turning of independent_filter.
**To Reproduce**
Using Deseqstats(dds,.....) with my own dataset

**Expected behavior**
non-nan p_values and p_adj values

**Screenshots**
![image](https://github.com/owkin/PyDESeq2/assets/135536839/7ece695e-ff38-4e08-a811-e5291f634ddd)

**Desktop (please complete the following information):**
 - OS: HPC virtual env
 - Version: latest, unsure how to check exactly

**Additional context**
I am a beginner, and would love to get some advice on what might be happening here.

**Comment by BorisMuzellec** [comment]
Hi @jairaj-mathur, given that you turned independent filtering off these NaN values are probably due to outlier filtering. Can you try setting `cooks_filter=False` in `DeseqStats`?

**Comment by jairaj-mathur** [comment]
Now it works, I am not having the NaN values. Could you please what independent and cooks filtering does, and why I dont have NaN values anymore? Does this affect the correctness of the analysis in any way?

**Comment by BorisMuzellec** [comment]
You're welcome! The independent and Cooks filtering aim to reproduce what is implemented in the original DESeq2 package, see [here](http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#pvaluesNA) for details (in R, sorry). 

Unfortunately PyDESeq2 doesn't have a vignette as detailed as the one I just linked yet. Something to think about for the future!
