### ISSUE TITLE
Convert 'PyDeseqStats' object into a DataFrame or export as CSV

### ISSUE THREAD

**Issue by alexisthermofisher** [owkin/PyDESeq2#149]
I'm am trying to export the data produced from stat_res.summary() as either a pandas dataframe or a csv file. Is there a way to convert 'DeseqStats' objects into pandas dataframes?

**Comment by BorisMuzellec** [comment]
Hi @alexisthermofisher, once `stat_res.summary()` is run, `stat_res` gets a `results_df` attribute, which is a pandas dataframe. You can export as CSV it with `stat_res.results_df.to_csv('foo.csv')`.
