### ISSUE TITLE
scverse integration

### ISSUE THREAD

**Issue by grst** [owkin/PyDESeq2#15]
Hi, 

congrats on the launch of PyDESeq2 -- I've been waiting for that for ages. 

I'm a core developer of [scverse](https://scverse.org/), and we want to foster interoperability of python packages for (not only single-cell) omics data analysis. I was wondering if you would be interested in integrating PyDESeq2 with our [ecosystem](https://github.com/scverse/ecosystem-packages/). This would greatly streamline leveraging PyDESeq2 for (pseudo-bulk) single-cell analysis for many users. 

## What would you be required to do? 
We have a [checklist for becoming an ecosystem package](https://github.com/scverse/ecosystem-packages/) mostly related to software quality. I believe you tick most of it already. 

The only important point would be to use our [`AnnData` datastructure](https://anndata.readthedocs.io/en/latest/). AnnData is the Python equivalent of Bioconductor's `SummarizedExperiment`, and allows to store a gene expression matrix (`X`) together with sample metadata (`obs`) and variable metadata (`var`) in a single object. It also allows to store unstructured information (`uns`) (e.g. the design factor), or DE results in as a data frame aligned to variables (`varm`). AnnData objects can be serialized to disk (h5/zarr) and are easy to share. 

At the very least, you'd need to support this in addition to `counts_df`/`clinical_df`, but it could even make sense to switch to AnnData internally.

## What do you gain?
 * Interoperability with scverse tools and potentially a larger user base.
 * Be recognized on the scverse website as approved ecosystem tool
 * We offer a best-practice [cookiecutter template](https://github.com/scverse/cookiecutter-scverse) which would also help you get started on a readthedocs documentation website (#7). 
 * You can use our [discourse forum](https://discourse.scverse.org/) as a channel to provide user support 

Let me know what you think! 
Best, 
Gregor

**Comment by BorisMuzellec** [comment]
Hi Gregor,

Thanks a lot, we're very excited by this idea (and we were actually secretly considering using AnnData at some point anyway :) ).

Right now we have some more pressing points to deal with (e.g. building documentation and enjoying Christmas holidays), but we're happy to start working on the integration after that.

Let's stay in touch!

Best,
Boris

**Comment by grst** [comment]
I would like to highlight again the scverse cookiecutter template: https://github.com/scverse/cookiecutter-scverse (It might have gotten lost in the previous message). 

It's fair enough if you don't want to switch to the template anymore at this stage, but it would get you a bunch of things for free that you are currently working on, e.g. code coverage, notebook examples (plus additional pre-commit checks and pure pyproject.toml-based build system)

**Comment by BorisMuzellec** [comment]
Hi Gregor, thanks for the suggestion. Not sure that we'll switch to the cookiecutter template entirely but we've had a look at it and we plan to draw inspiration from it indeed :) .
