### ISSUE TITLE
Unable to figure out how to obtain variance stabilizing transformation of the entire dataset [BUG] 

### ISSUE THREAD

**Issue by jairaj-mathur** [owkin/PyDESeq2#150]
**Describe the bug**
Sorry if I wrongly put this in the bug category, but can I obtain the variance stabilizing transformed dataset for my ENTIRE dataset? I have 4 time points and 3 drug concentrations in my dataset, and I am interested in obtaining a PCA plot for my entire dataset. I have read that transforming the dataset makes the PCA more accurate, and I am wondering, can I load all these conditions and get the transformed data. I can see that stat_res.dds.layers['normed_counts'] could be what I am looking for, but this is usually for one comparision at a time (timeA+drug_concA vs time_A+no_drug). 

**Desktop (please complete the following information):**
 - OS: HPC virtual env 
 - Version ?

**Comment by BorisMuzellec** [comment]
I'm not sure I understand precisely what you are trying to do but please see the documentation regarding vst: 

https://pydeseq2.readthedocs.io/en/latest/api/docstrings/pydeseq2.dds.DeseqDataSet.html?highlight=vst#pydeseq2.dds.DeseqDataSet.vst

PyDESeq2 does not implement PCA, so you will have to use a third-party package such as [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html) (or any other).

**Comment by BorisMuzellec** [comment]
Hi Jairaj, if you just want to perform VST (and then PCA), you dont' need to run the stats, lfc_shrink and so on.

Something like 

```
dds = DeseqDataSet(counts=my_counts, clinical=my_annotations, design_factors=my_design_factors)
dds.vst(use_design=True) # assuming you want to use the design matrix in the VST
```

will store the results of VST in `dds.layers["vst_counts"]`. You can then use scikit-learn to apply PCA.

**Comment by jairaj-mathur** [comment]
This worked well for me, thank you!
