### ISSUE TITLE
How to create dispersion vs means plot for dataset by calculating means and dispersions from pydeseq2?[BUG] 

### ISSUE THREAD

**Issue by jairaj-mathur** [owkin/PyDESeq2#151]
Hi all, could anyone point me towards how can I obtain the corresponding values of means and dispersion for each gene, so that I can create a dispersion vs means plot?

Edit: I apologize, I dont know how can I make posts without the bug label.

**Comment by BorisMuzellec** [comment]
Assuming `dds` is the name of your `DeseqDataSet`, after runnning `dds.deseq2()`  you'll find the dispersions in `dds.varm["dispersions"]` and the normalized means in `dds.varm["_normed_means"]`.

See the [tutorials](https://pydeseq2.readthedocs.io/en/latest/auto_examples/index.html) for more details.

Note also that starting from v0.3.5 `DeseqDataSet` has a [`plot_dispersions()`](https://pydeseq2.readthedocs.io/en/latest/api/docstrings/pydeseq2.dds.DeseqDataSet.html#pydeseq2.dds.DeseqDataSet.plot_dispersions) method.

**Comment by jairaj-mathur** [comment]
Hi Boris. Thank you, I was able to do this and get a nice plot
sns.scatterlpot(log10(dds.varm['_normed_means'], dds), log10(dds.varm['dispersions']) 

I really appreciate all your help so far!
