### ISSUE TITLE
Advice on statistical analysis for multifactor

### ISSUE THREAD

**Issue by jairaj-mathur** [owkin/PyDESeq2#155]
Hi all
[version: 0.3.5]
Thank you for all the help so far. I have 4 time points after drug addition, and 3 drug concentrations and 3 replicates each in my bulk RNA seq data. From the tutorials, it is clear that I would create 2 columns in clinical_df, time and dose and that this is a multi factor analysis.

I am unable to understand how to perform the statistical analysis here. In the tutorial, it says DeseqStats(dds, contrast=["condition", "B", "A"].  In my understanding, this gives us DEGs between all samples with condition A and all samples with condition B, regardless of the group. 
Now that pydeseq2 supports n-level factors  (#101), I would like to find the DEGs between dose=dose1 and dose =dose2 for time = time1, and not regardless of the time. How can I do this? 
I apologize of this is a very naive question.
![image](https://github.com/owkin/PyDESeq2/assets/135536839/9236111a-e5d1-41f0-9ded-41b3efc8fa25)

**Comment by BorisMuzellec** [comment]
Hi Jairaj, as pydeseq2 does not implement interaction (nor continuous) terms for now, I think the simplest way to perform your analysis would  be to group both the drug and time factors in a single factor (let's call it `"dose_and_time"`), that would contain all 12 possible combinations, i.e. `[dose1_time1, dose1_time2, ..., dose3_time4]`. 
Then, you would perform the analysis with `contrast=['"dose_and_time"', "dose2_time1", "dose1_time1"]`.

Would this make sense?

On a side note, for topics that are not related to a bug or a new feature request, I would prefer if you could write your questions on the [scverse ecosystem discussion forum](https://discourse.scverse.org/c/ecosystem/) (mentioning in title that the question is about pydeseq2), so as to keep the github issues section for subjects related to code improvement. Thanks!

**Comment by jairaj-mathur** [comment]
Hi Boris. Thank you so much, yes I can do that, it wouldn't affect the correctness of the results, right?
Apologies for crowding the github issues with questions, I wasn't aware of the scverse forum, that looks very useful. Thank you for all the help so far!

**Comment by vcabeli** [comment]
Hello @jairaj-mathur,
No it won't affect the correctness of your results, it is equivalent to using interaction terms in DESeq2 as explained in the vignette : 
https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#interactions
> Using this design is similar to adding an interaction term, in that it models multiple condition effects which can be easily extracted with results.
