### ISSUE TITLE
`clinical` parameter in `classDeseqDataSet` class

### ISSUE THREAD

**Issue by abearab** [owkin/PyDESeq2#156]
Your `classDeseqDataSet` class has a parameter that called `clinical`. However, your tool can be used for non clinical tasks so I would change that into a more general name.

**Comment by BorisMuzellec** [comment]
Hi @abearab, indeed, this is a good point.

What would you suggest? After a short survey it seems that most DGE packages name this parameter something like `columns` or 'column_data`.

**Comment by abearab** [comment]
Thanks for your response.

I have seen `colData` in R packages, too. I’m not sure if that make sense here since samples are actually rows in AnnData object. I would go with something more general like `meta_data`.
