### ISSUE TITLE
[Feature request] Threshold-based Wald test

### ISSUE THREAD

**Issue by amberT15** [owkin/PyDESeq2#158]
I think currently the Wald test is testing based on the null hypothesis of  FC = 0. While in a lot of experiments we care more about a banded null hypothesis (FC > smth like 1.5).

In DESeq2 theres an option of passing the parameter lfcThreshold into the Wald test.  Would be nice to have this feature added? Or if it already exist I couldn't find it in the documentation.

Thanks!

**Comment by BorisMuzellec** [comment]
Hi @amberT15, indeed Wald tests are currently based on the null hypothesis LFC = 0.

There is no `lfcThreshold` parameter yet. I agree that this feature would be a nice addition, but unfortunately I probably won't be able to find the time to implement in the next few weeks.

Meanwhile, I'm happy to help anyone with a PR on this topic :).
