### ISSUE TITLE
Tutorial including interactions terms in the design

### ISSUE THREAD

**Issue by khalilouardini** [owkin/PyDESeq2#183]
**Is your feature request related to a problem? Please describe.**
Not clear how the user can include interaction terms in the design matrix.

**Describe the solution you'd like**
A short tutorial, showing typical use cases of interaction terms, e.g categorical/categorical or continuous/categorical

**Additional context**
related to [PR#81](https://github.com/owkin/PyDESeq2/pull/181)

**Comment by abearab** [comment]
@BorisMuzellec – Hope you are doing well. Can you provide some example codes on how to use the interactions terms? It seems there are many specific considerations during the implementation which made it hard for me to understand how to use it and a short descriptions would be very helpful and appreciated. Thanks
