### ISSUE TITLE
How to load synthetic bulk RNA count matrix and metadata

### ISSUE THREAD

**Issue by victorsanchezarevalo** [owkin/PyDESeq2#19]
Hi, again congrats for the great work.

I am trying to load my own data, I have a count matrix obtained with Featurecounts but I don't know how to do it. Any guide please?
Did it work with a data frame? Should I load the count matrix and the metadata separately?

Thanks for your help.

Best

Victor

**Comment by arthurPignetOwkin** [comment]
Hi Victor, 

We've built the docstrings in a more readable documentation, the PR should be merged shortly to push the docs to ReadTheDocs. However, it appears clearly that we need a dedicated tutorial/api to load external data. We added that on our roadmap. 

Meanwhile, in your specific case, you may want to have a look at the start notebooks and [you can even run them from your browser](https://mybinder.org/v2/gh/owkin/PyDESeq2/HEAD?labpath=notebooks%2Findex.ipynb) (disclaimer: myBinder can be a bit slow), and try to adapt it to your own data. 
To do so you can look at the [synthetic data we generated for testing purpose](https://github.com/owkin/PyDESeq2/tree/main/tests/data), that we load with [pydeseq2.utils.load_data](https://github.com/owkin/PyDESeq2/blob/main/pydeseq2/utils.py#L20) function, and see how they differ from your data. 

Let us know how it is going for you! 

Best,
Arthur

**Comment by victorsanchezarevalo** [comment]
Thanks Arthur,

I have been able to load the data an run the complete analysis with the test files. I tried now with my own data and I have some problems with NaNs in padj values. I have opened a new issue. Could you help me, please?

Thanks again! I am really excited to used PyDESeq2!

Best

Victor

**Comment by BorisMuzellec** [comment]
Closing this issue as it was answered in #35 (trying to keep issues limited to a single topic)
