### ISSUE TITLE
EnvironmentFileNotFound

### ISSUE THREAD

**Issue by DarthRevan109** [owkin/PyDESeq2#20]
Hi all,
Attempting to install PyDESeq2 and running into this issue when attempting to create the conda environment. 
`conda env create -f environment.yml`

I get the following error:
EnvironmentFileNotFound: '......\environment.yml' file not found

Any suggestions for a fix? 

Thanks,

**Comment by BorisMuzellec** [comment]
Hi! Are running this command from the root of the repo?

Alternatively, `pydeseq2` is now available on PyPI! I.e. you may install it by running 

`pip install pydeseq2`
