### ISSUE TITLE
Using data from Kallisto

### ISSUE THREAD

**Issue by PelFritz** [owkin/PyDESeq2#210]
**Is your feature request related to a problem? Please describe.**
When one maps fastq data with kallisto and uses Tximport from R to import the data, we get counts and TPMs but these seem to have been processed/normalized already.  So data is not intergers as required by pyDeseq2.

I have built a streamlit app that runs untop of pyDeseq2 but unless you have interger counts it will throw an error

**Describe the solution you'd like**
Can we have something that import Kallisto/Salmon based data?

**Comment by vcabeli** [comment]
Hello @PelFritz,

As far as I know, if you have float count estimates from kallisto the solution is simply to round them to get integers.
It seems to be what tximport does, see the line from DESeq2 : https://github.com/thelovelab/DESeq2/blob/6947d5bc629015fb8ffb2453a91b71665a164483/R/AllClasses.R#L412 
and  Dr. Michael Love's answer here https://support.bioconductor.org/p/88763/

**Comment by PelFritz** [comment]
@vcabeli thanks for pointing this out. I will just adjust my app to take this into consideration
