### ISSUE TITLE
Why is replacement not done if it would result in all zero counts?

### ISSUE THREAD

**Issue by chubukov** [owkin/PyDESeq2#238]
[here](https://github.com/owkin/PyDESeq2/blob/39b6a373abb85991b5ac50f5f5b26a1a290d890b/pydeseq2/dds.py#L965C1-L966C2) and [here](https://github.com/owkin/PyDESeq2/blob/39b6a373abb85991b5ac50f5f5b26a1a290d890b/pydeseq2/dds.py#L1023-L1024) there is a filter for not doing outlier replacement or refitting if the result of the replacement would be all zero counts.
```
        # Only refit genes for which replacing outliers hasn't resulted in all zeroes
        new_all_zeroes = (self.counts_to_refit.X == 0).all(axis=0)
```

```
        # Only replace if genes are not all zeroes after outlier replacement
        to_replace[to_replace] = ~new_all_zeroes
```

Why is this the right thing to do? If I have zero counts in all but one sample, and a large count in the single outlier sample, why wouldn't the right result be to remove the outlier?

Is this consistent with what the R DESeq2 package does?

**Comment by BorisMuzellec** [comment]
Hi @chubukov, thanks for pointing this out.

I just tested the example you provide in #237 in the original R DESeq2 package. The resulting behavior is to replace outliers even if it leads to the gene only having zero counts, in which case the `baseMean` is then set to 0 and all columns in the results dataframe to `NaN`.
