### ISSUE TITLE
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed. 

### ISSUE THREAD

**Issue by lizelx** [owkin/PyDESeq2#242]
Hello,
I'm trying to conduct a multifactor analysis on my data. I completely prepared the data in accordance with the tutorial, and at the stage of statistical analysis (.summary() function) I received the error “too many indices for array: array is 1-dimensional, but 2 were indexed”. Moreover, if I reduce the number of genes from 30 thousand to 10 genes, no error occurs. Could you tell me what is the reason?

**Comment by BorisMuzellec** [comment]
Hi @lizelx, could you share the code that you run, and the complete error traceback?

**Comment by lizelx** [comment]
Thanks for the quick response! Here's a link to the notebook if it's convenient for you - https://colab.research.google.com/drive/1hMunKsc65SCIAOX6QTdRVwvZpbI6DE4c?usp=sharing
[file.csv](https://github.com/owkin/PyDESeq2/files/14405119/file.csv)

**Comment by laudmt** [comment]
Hello, it also makes TDE workflow fail on pydeseq2 0.4.5 in TumoralExpressionScoring:

https://github.com/owkin/target_discovery_engine/actions/runs/8049835848/job/21984073871?pr=464

**Comment by lizelx** [comment]
> @lizelx and @laudmt I've found where the bug comes from, I'm currently trying to fix it. Meanwhile I yanked v 0.4.5 on pypi

Thank you very much for your quick feedback and help in resolving this case. It worked well!

**Comment by chubukov** [comment]
Hi, I still get the same error with #1d6dda6

>pydeseq2/ds.py", line 536, in _independent_filtering
>        residual = num_rej[num_rej > 0] - lowess_res[num_rej > 0, 1]
>
>     too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by chubukov** [comment]
I still get this error with #8fcf5c1

>      pydeseq2/ds.py", line 536, in _independent_filtering
>        residual = num_rej[num_rej > 0] - lowess_res[num_rej > 0, 1]

>    too many indices for array: array is 1-dimensional, but 2 were indexed
