### ISSUE TITLE
[BUG] All padj is same when independent_filter = False

### ISSUE THREAD

**Issue by kgod336336** [owkin/PyDESeq2#245]
Hello.
I am glad to use DESeq2 in python !
But unfortunately, I found a putative bug.

**Describe the bug**
When I turn independent_filter = False, to use BH method for padj as below,

stat_res = DeseqStats(dds, inference=inference,independent_filter=False)

returned padj has same value.(in the case of demo data was loaded ,padj = 0.001297)

**To Reproduce**
1. pyDeseq2 is version 0.4.6
2. run plot_minimal_pydeseq2_pipline.ipynb in VScode
3. change "stat_res = DeseqStats(dds, inference=inference)" to " stat_res = DeseqStats(dds, inference=inference,independent_filter=False)"

**Expected behavior**
stat_res.summary() ,  the results is,

Log2 fold change & Wald test p-value: condition B vs A
          baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
gene1     8.541318        0.632813  0.289100  2.188903  0.028604  0.001297
gene2    21.281240        0.538722  0.147482  3.652791  0.000259  0.001297
gene3     5.010124       -0.633180  0.291892 -2.169227  0.030065  0.001297
gene4   100.517967       -0.412102  0.118626 -3.473970  0.000513  0.001297
gene5    27.142454        0.582065  0.154703  3.762464  0.000168  0.001297
gene6     5.413043        0.001457  0.310311  0.004697  0.996253  0.001297
gene7    28.294025        0.134375  0.149231  0.900450  0.367881  0.001297
gene8    40.358341       -0.270656  0.136399 -1.984300  0.047222  0.001297
gene9    37.166183       -0.212715  0.133241 -1.596466  0.110385  0.001297
gene10   11.589326        0.386011  0.244587  1.578217  0.114516  0.001297
Running Wald tests...
... done in 0.01 seconds.

**Desktop (please complete the following information):**
 - OS: Ubuntu (using remote via VScode)
 - Version 22.04.4 LTS

**Additional context**
When I used my own data, the padj values in that result were same, but not 0.001297. 

Thank you !

**Comment by BorisMuzellec** [comment]
Hi @kgod336336, good catch! Thanks for reporting this bug, it should be fixed now.
