### ISSUE TITLE
contrast matrix

### ISSUE THREAD

**Issue by Intron7** [owkin/PyDESeq2#27]
First of all thank you for the great work. As far as I can see it in the code there is no way to use a contrast if I have 3 conditions like treatment 1 and 2 and compare it to the WT separately. Do you already support multifactor designs for paired analysis? 

Also it would be really great if you reduce and test this package with a lower numpy version so it doesn't break environments upon installation.

**Comment by BorisMuzellec** [comment]
Hi @Intron7, for now multifactor designs are not supported, but we are working on it!

As for the numpy version, we'll test lower versions if this is an issue that several users encounter, but I can't guarantee that we'll switch to a lower one depending on the results we get.

**Comment by BorisMuzellec** [comment]
Hi @Intron7, pydeseq2 now supports multifactor designs for paired analysis (as long as each factor is bi-level), c.f. the "Multifactor Analysis" part of the [Getting started tutorial](https://pydeseq2.readthedocs.io/en/latest/auto_examples/plot_minimal_pydeseq2_pipeline.html#).

As for the numpy version, we're sorry but we are not currently planning to reduce the current requirements as we want to think ahead and avoid any future deprecations.

I'm closing this issue, but please don't hesitate to open a new one if you have comments and/or suggestions!
