### ISSUE TITLE
How to process gene expression data from Affymetrix in Python

### ISSUE THREAD

**Issue by abearab** [owkin/PyDESeq2#270]
I'm trying to perform some basic DE analysis on https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE171053. How could I do that with pyDESeq2?

I saw [this](https://www.biostars.org/p/381578/) in biostars from 5 years and hopefully now the answer is pyDESeq2!
> Don't do that in python. Use established R packages to analyse microarrays. See this [tutorial](https://bioconductor.org/packages/devel/workflows/vignettes/maEndToEnd/inst/doc/MA-Workflow.html).

**Comment by vcabeli** [comment]
Hello @abearab, unfortunately pyDESeq2 is not compatible with affymetrix data, since the DESeq2 algorithm is designed for count data with a particular distribution.

I would use limma in R, or you could try looking for a maintained python implementation of limma but I'm not sure that exists
