### ISSUE TITLE
[BUG] vst() throws a runtime error when parametric fitting defaults to mean because vst_fit_type is still set to parametric

### ISSUE THREAD

**Issue by dguin** [owkin/PyDESeq2#311]
vst_transform() runs into the runtime error when parametric fit does not converge and the algorithm picks the mean method.

**Expected behavior**
In vst(), set self.vst_fit_type to mean if parametric falls back to the mean-based method.

 - OS: Ubuntu
 - Version 0.4.10

**Comment by dguin** [comment]
Happy to fix this bug:

I think simply need to add a line to set `vst_fit_type` to mean after `vst_fit`
```
self.vst_fit(use_design=use_design)
self.vst_fit_type = self.uns["disp_function_type"]
self.layers["vst_counts"] = self.vst_transform()
```

**Comment by BorisMuzellec** [comment]
Hi @dguin, #314 should do the trick. Let me know if you're still encountering any issue!
