### ISSUE TITLE
Improvement for DeseqDataSet documentation

### ISSUE THREAD

**Issue by ozanozisik** [owkin/PyDESeq2#316]
In DeseqDataSet documentation, ref_level is described as below:

ref_level : list or None
        An optional list of two strings of the form ``["factor", "test_level"]``
        specifying the factor of interest and the reference (control) level against which
        we're testing, e.g. ``["condition", "A"]``. (default: ``None``).

Use of "test_level" in the example while requiring reference level is confusing. It will be better if the example is ["factor", "ref_level"] (like in the description of build_design_matrix) or ["factor", "reference_level"].

**Comment by BorisMuzellec** [comment]
Hi @ozanozisik, thanks for the suggestion! Feel free to open a PR :)

**Comment by BorisMuzellec** [comment]
Closing this as reference levels were deprecated by #328
