### ISSUE TITLE
[BUG]  AttributeError: 'DeseqDataSet' object has no attribute 'to_picklable_anndata'

### ISSUE THREAD

**Issue by nandithasreeni** [owkin/PyDESeq2#341]
**Describe the bug**
After executing dds.deseq2() statement successfully, wanted to store the ann data in pickle file.
 
**To Reproduce**
run the below statement
with open("result_adata.pkl", "wb") as f:
    pkl.dump(dds.to_picklable_anndata(), f)

then you get the error message : 
AttributeError: 'DeseqDataSet' object has no attribute 'to_picklable_anndata'

**Expected behavior**
this should have saved the data in the file. Checked in github for the code implementation, 
def to_picklable_anndata(self) -> ad.AnnData: => is defined but this is not working.

**Screenshots**
![image](https://github.com/user-attachments/assets/bbe12f6e-255e-4cba-b08d-1f5bdded6f02)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by BorisMuzellec** [comment]
Hi @nandithasreeni, this is because `to_picklable_anndata` is part of the `0.5.0rc1` pre-release.

You should either:
-  refer to the `stable` version of the docs (https://pydeseq2.readthedocs.io/en/stable/auto_examples/plot_pandas_io_example.html#sphx-glr-auto-examples-plot-pandas-io-example-py),
- or install the pre-release (`pip install --upgrade --pre pydeseq2`).

**Comment by nandithasreeni** [comment]
Hi BorisMuzellec,

   Thanks for very prompt reply. However, the problem is not solved.
   1.    I'm referring the same document which you have provided in the link.
   2.    Installed pre-release and tried again, didnt worked. 
  
Landed up with same error message. Is it link, first I need to uninstall and then install the pre-release?

**Comment by nandithasreeni** [comment]
Sorry, I stand correct. This document and installation worked.

Thanks a lot @BorisMuzellec
