### ISSUE TITLE
NaNs in padj

### ISSUE THREAD

**Issue by victorsanchezarevalo** [owkin/PyDESeq2#35]
Hi.

I am performing my first analysis with PyDESeq2 but I obtain several NaNs when I use the function 'stat_res.padj' so when I try to run 'stat_res.lfc_shrink()' I have NaNs in log2FoldChange and lfcSE. I have checked my count matrix but I dont have NaNs. Could you help me please?

Thanks a lot!

Victor

**Comment by BorisMuzellec** [comment]
Hi Victor, similarly to DESeq2 you may obtain NaNs in the pvalues or adjusted pvalues if within a gene there is a large outlier count, or if a gene has been filtered by independent filtering (which you can turn off using the `independent_filter` attribute of the `DeseqStats` class).

Log2FoldChange and lfcSE are supposed to be NaN only if for this gene all samples have zero counts. Could you check whether this is the case? If not, there could be a bug.

**Comment by victorsanchezarevalo** [comment]
Thanks Boris!

Great, It worked perfectly!

Turning off `independent_filter` solved the problem.

Best

Victor

**Comment by BorisMuzellec** [comment]
Happy that this was helpful! Hopefully the docs will soon be more complete
