### ISSUE TITLE
Support type hinting

### ISSUE THREAD

**Issue by illumination-k** [owkin/PyDESeq2#39]
First of all, thanks for your great project!

Recently, type hinting is becoming a great feature of python. It is a profitable feature for IDE complementation, static analysis, removing bugs, and people reading codes for the first time. 

Is there a plan to support type hinting by mypy? 
If this is a contribution, I consider creating a PR.

FYI:
Numpy officially prepared the [numpy.typing](https://numpy.org/devdocs/reference/typing.html) modules and microsoft recommends [pandas-stub](https://github.com/pandas-dev/pandas-stubs). Unfortunately, matplotlib, scipy, and sklearn stubs are not supported in [typeshed](https://github.com/python/typeshed) but developing in [python-type-stubs](https://github.com/microsoft/python-type-stubs).

**Comment by BorisMuzellec** [comment]
Hi @illumination-k, thanks for the initiative, this is a great suggestion! Type hinting with mypy would definitely be a plus.

We're currently writing the contribution guidelines, they should be ready within a week.

If you're interested in contributing, we're looking forward to your PR!
