### ISSUE TITLE
Variance stabilizing transformation function

### ISSUE THREAD

**Issue by victorsanchezarevalo** [owkin/PyDESeq2#41]
Hi,

Would it be possible to use 'Variance stabilizing transformation function' in the future, I have look for it in the documentation but I did not find it.

What would you recomend for heatmaps?

Thanks!

Vic

**Comment by BorisMuzellec** [comment]
Hi Victor, 

Indeed VST is not available yet in PyDESeq2, but we plan to implement it soon (probably after we make the changes required to integrate scverse #15 though, so we'll ask for your patience :) ).

For now the only normalisation method that is supported in PyDESeq2 is [median-of-ratios](https://pydeseq2.readthedocs.io/en/latest/api/preprocessing.html), which is probably not recommended for heatmaps...

**Comment by victorsanchezarevalo** [comment]
Thanks Boris.

I really appreciate your availability, always answering super fast!! I will wait for the implementation, It is great the job that you have done with PyDESeq2. I will try with median-of-rations in the mean time.

Best

Victor
