### ISSUE TITLE
Issue with Cooks Refitting if Less Than Three Replicates

### ISSUE THREAD

**Issue by LawrenceGordon** [owkin/PyDESeq2#43]
I am working with a small dataset (two unaffected, two affected) samples. I have been running into an error in the utils function `robust_method_of_moments_disp()` which is called in `DeseqDataSet.calculate_cooks()`. The core issue I've found is in the `trimmed_variance()` function:
```
def trimmed_variance(x, trim=0.125, axis=1):

    rm = trimmed_mean(x, trim=trim, axis=axis)
    sqerror = (x - rm) ** 2
    # scale due to trimming of large squares
    return 1.51 * trimmed_mean(sqerror, trim=trim, axis=axis)
```
The returned value for `rm` is in the shape (n_samples, ) while the shape of `x` is (n_sample, n_genes). This leads to an error like follows:
```
ValueError
Unable to coerce to Series, length must be n_genes: given n_samples
```
I was able to bypass the error by using the `trimmed_cell_variance()` function instead, however a stronger fix to the issue is outside of my abilities, as I'm unsure the actual desired shape of `sqerror`.

**Comment by BorisMuzellec** [comment]
Thanks for reporting this bug @LawrenceGordon.
I think I've identified where it comes from, I've opened a PR (#44) to fix it. I'll let you know when it's merged :).

**Comment by BorisMuzellec** [comment]
I've merged a PR to fix this issue. It'll be part of the next PyPI release.
