### ISSUE TITLE
Discrepancy between PyDESeq2 and DESeq2 on TCGA-cancer miRNA data

### ISSUE THREAD

**Issue by BorisMuzellec** [owkin/PyDESeq2#45]
@joe-sclin I'm moving your comment to a dedicated issue:

> First of all, thank you for your contribution to develop Python version of DESeq2.
> 
> I tried to apply the synthetic layout for several TCGA-cancer miRNA analysis. Percentage for baseMean, log2FoldChange and  stat between PyDESeq2 and DESeq2 are normal (less than 2%), but lfcSE had almost 10% difference and even much more for pvalue and padj.
> Is current PyDESeq2 only optimised for Gene Expression Quantification data?

_Originally posted by @joe-sclin in https://github.com/owkin/PyDESeq2/issues/36#issuecomment-1378857459_

**Comment by BorisMuzellec** [comment]
@joe-sclin Did you install PyDESeq2 from PyPI or from source? In the former case, could you tell me which version number you have? 

PyDESeq2 wasn't tested on miRNA data (which I'm not very familiar with) so this could be an explanation.

Generally speaking we can't guarantee that you'll obtain the exact same results with both packages, as e.g. we are relying on different optimization packages in PyDESeq2. 

If you think that those differences are problematic in the present case (e.g. they lead to different biological conclusions) and that they could be due to a bug I can look into them, but I'll need more details.

**Comment by joe-sclin** [comment]
I installed PyDESeq2 from PyPI with version 0.1.1.
I worked on TCGA-BRCA (and other tested cancer dataset from example) miRNA Expression Quantification, only different in pvalue and padj caused problems.
I am still working on troubleshooting to determine source of difference

**Comment by joe-sclin** [comment]
Update: I can reproduce DESeq2 result for TCGA miRNA dataset using the following setting:
PyDESeq2 ver. 0.2.1
Skipping dds.fit_dispersion_prior()
refit_cooks =  True

Average 93% identical DE miRNA and 0.03% difference in LFC on 12 TCGA dataset
Difference between DESeq2 and PyDESeq2 is larger for small number of DE miRNA
