### ISSUE TITLE
Wald-test error if no Cook distance refit is performed

### ISSUE THREAD

**Issue by slieped** [owkin/PyDESeq2#46]
First,  I would like to thank you for this amazing tool!

The problem I am facing result of running the _stat_res.run_wald_test()_ function
I have followed the step-by-step tutorial with my own data. I skipped the Cook distance-based refit.
As a result, my original DeseqDataSet object DO NOT have the "_replaced_" attribute.

This cause an error in DeseqStats.py/run_wald_test (line 303) , where it checks if it needs to correct the p-values based on Cook refiting. 

My guess is that the _replaced_ attribute should be initialized (?maybe set to pd.Series[0]?) when calling the DeseqDataSet class object.

This is solved if I force dds.replaced = pd.Series[0] and/or if I run the _dds.refit()_ function

Let me know if you require further info to reproduce this issue

**Comment by slieped** [comment]
Ok, NVM.

Just debugged it and it seems that its related to the creation of the DeseqDataSet.
If I set the parameter refit_cooks=False when init the object, this problem is not present anymore.

I guess it should be stated somewhere, tho, that if you init with this parameter, you must perform the refit() afterwards?

Thank again for the tool!

**Comment by BorisMuzellec** [comment]
Hi @slieped, thank you for your interest in PyDESeq2!

This is valuable feedback. Indeed there should be a warning message at least.

To summarize, the issue arises if you initialize a `DeseqDataSet` with `refit_cooks=True` (which is  the default), but do not run the `dds.refit()` before running the `run_wald_test()` (or `summary()`) method of a `DeseqStats` object built on top of it, is that correct?

**Comment by slieped** [comment]
Thats correct, yes!
