### ISSUE TITLE
improve on the doc api

### ISSUE THREAD

**Issue by maikia** [owkin/PyDESeq2#52]
for the api it would be great to have a nicer view:

- have a list of the class attributes of DeseqDataSet and DeseqStats the same way the methods are listed? (like in e.g. [squidpy](https://squidpy.readthedocs.io/en/stable/classes/squidpy.im.ImageContainer.html))

- do not list the `__init__` method in the doc. It seems like it doesn't add much information compared to the description of the class, which already lists the arguments.
cc @BorisMuzellec

**Comment by BorisMuzellec** [comment]
Closing - this was implemented
