### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by cthoyt** [owkin/PyDESeq2#7]
Right now it doesn't appear that there's any documentation (e.g. on ReadTheDocs). I'd highly suggest adding this to make this package more accessible for potential users

**Comment by BorisMuzellec** [comment]
Hi @cthoyt, thanks for the suggestion! This is definitely at the top of our TODO list.

**Comment by sdhutchins** [comment]
> Hi @cthoyt, thanks for the suggestion! This is definitely at the top of our TODO list.

Feel free to use the community to help as well. I'm sure a lot of people in the community would contribute to that to-do list if you all converted it into issues.  @BorisMuzellec

**Comment by BorisMuzellec** [comment]
That's a great idea @sdhutchins :). We're currently thinking of a list of issues and features with the team, we'll post them ASAP.

**Comment by victorsanchezarevalo** [comment]
Absolutely AWSOME to have DESeq2 in python!! Congrats!! I am trying to use it but I am having problem loading my on data. Any guide to begin, please?

Best and thanks for this gift to the community.

Victor

**Comment by BorisMuzellec** [comment]
Hi Victor, thanks a lot! We're excited to see that our work is reaching an audience :).

We're going to build the docstrings in a more readable documentation shortly. 

Meanwhile, you can have a look at the starter notebooks - [you can even run them from your browser](https://mybinder.org/v2/gh/owkin/PyDESeq2/HEAD?labpath=notebooks%2Findex.ipynb) (disclaimer: myBinder can be a bit slow).

Also, feel free to open a dedicated issue so that we can help you with the problems you're encountering with your data :).

Best,
Boris

**Comment by BorisMuzellec** [comment]
Update: a rather barebones version of the API documentation is now available on [ReadTheDocs](https://pydeseq2.readthedocs.io/en/latest/).

We are still working on improvements (improving readability, writing tutorials, etc.).

**Comment by victorsanchezarevalo** [comment]
Great Boris!.

Thank you very much for the update, I really appreciate! 

I have been on holidays but next week I will try several analysis with PyDESeq2. I am really interested in the package. 

Best

Victor

**Comment by BorisMuzellec** [comment]
Hi everyone,

Additionally to the [API documentation](https://pydeseq2.readthedocs.io/en/latest/api/index.html), we just wrote a [Getting Started](https://pydeseq2.readthedocs.io/en/latest/auto_examples/plot_minimal_pydeseq2_pipeline.html#) example in the docs.

I'm closing this issue for now, but please don't hesitate to open new ones if you have requests or ideas for improvement!
