### ISSUE TITLE
[BUG] Import  issue in plot_minimal_pydeseq2_pipeline.py

### ISSUE THREAD

**Issue by Morteza-M-Saber** [owkin/PyDESeq2#76]
The import that works for me in `plot_minimal_pydeseq2_pipeline.py` is:

>from pydeseq2 import DeseqDataSet, DeseqStats

Pydeseq2 was install by pip.

**Comment by Morteza-M-Saber** [comment]
Importing as instructed return error:
>from pydeseq2.dds import DeseqDataSet
>from pydeseq2.ds import DeseqStats
>ModuleNotFoundError: No module named 'pydeseq2.dds'

Yet replacing this with:
>from pydeseq2 import DeseqDataSet, DeseqStats
and then using

>dds = DeseqDataSet.DeseqDataSet(
    counts_df,
    clinical_df,
    design_factors="condition",
    refit_cooks=True,
    n_cpus=3,
)
works!

**Comment by BorisMuzellec** [comment]
Hi @Morteza-M-Saber, thanks for pointing this out!

Indeed, the `DeseqDataSet.py` and `DeseqStats.py` files were renamed `dds.py` and `ds.py` in a recent version of the code that is not available on PyPI yet.

As a result, there is a currently a discrepancy between the docs and the latest pip version: the docs describe the latest version of pydeseq2, that can only be installed from source.

We'll try to implement versioned documentations in the future to allow users to select docs that are relevant to the package version they currently have.

**Comment by Morteza-M-Saber** [comment]
Perfect, thanks to you and your great team.

Cheers,
