### ISSUE TITLE
How to get normalized expression values

### ISSUE THREAD

**Issue by Morteza-M-Saber** [owkin/PyDESeq2#77]
First, thanks for the amazing and much needed work.
In DeSeq2 its possible to output vst normalized expression values as output. Is there such possibility with pyDeseq2?

**Comment by BorisMuzellec** [comment]
Hi @Morteza-M-Saber,

Thanks you for your interest in our work.

VST is currently not available in PyDESeq2, but it is one of the features we plan to implement in the near future. 

We have written a [development roadmap](https://github.com/owkin/PyDESeq2#development-roadmap) to keep track of future features. Feel free to open issues if there are some features you’d like to see in the future that are not listed there, or even to [open a PR](https://pydeseq2.readthedocs.io/en/latest/usage/contributing.html#how-can-i-contribute)! 

Thank you for your patience!

Best,
Boris

**Comment by Morteza-M-Saber** [comment]
Great, thanks @BorisMuzellec ,
I would definitely love to contribute in this amazing tool. Not sure I have sufficient mathematics knowledge to accurately implement VST but I will give it a try by checking love's codes.

Thanks

**Comment by Morteza-M-Saber** [comment]
Just more point, is it possible to export normalized expression values based on sequencing depth calculated by pydeseq2?

**Comment by BorisMuzellec** [comment]
Hi again,

To clarify, implementing VST is in our TODO list. It should be available in roughly a month (maybe earlier), so if you can afford to wait you don't have to do anything :). But if you routinely use other features that are not listed in the development roadmap, this is valuable feedback for us.

Right now there's no direct way to get the normalized expressions values based on median-of-ratios that are used in the pipeline, but I feel like there should be one. I'll open a quick PR to add them as a `DeseqDataSet` attribute.

In the meantime you can access them with the following code (if your `DeseqDataSet` is named `dds`):

```normed_counts = dds.counts.div(dds.size_factors, 0)```

**Comment by Morteza-M-Saber** [comment]
Thanks again Boris,
Really appreciate it :)
