### ISSUE TITLE
DOC fix ugly type-hinting in the docs

### ISSUE THREAD

**Issue by BorisMuzellec** [owkin/PyDESeq2#86]
The type-hinting info makes the [API documentation](https://pydeseq2.readthedocs.io/en/latest/api/index.html) look quite ugly (cf the screenshot below).

<img width="798" alt="Capture d’écran 2023-02-21 à 17 49 48" src="https://user-images.githubusercontent.com/11092154/220408806-d61cb554-6dae-44bb-b341-e50562c0462e.png">

We should improve this by either removing unneeded ndarray type information (e.g. `[numpy.ndarray[Any, numpy.dtype[numpy._typing._generic_alias.ScalarType]]`, or making it more precise.

Also, function signatures (blue-shaded areas) should probably be left-aligned.

**Comment by illumination-k** [comment]
Adding following code to `conf.py` can improve ugly type
 
```python
needs_sphinx = "4.0"

autodoc_typehints_format = "short"
python_use_unqualified_type_names = True
```

![image](https://user-images.githubusercontent.com/43526984/220612520-6cff6ee7-286e-48bc-86d4-2b167f0fcc21.png)

In python 3.8, it is difficult to restrict ndarray shape (first any), but dtype information can be strict and it is helpful (For example, `count` should be `int`, and `size_factor shoud` be `float` etc.,).

In python 3.9 or greater, we can annotated ndarry shape such as 1D array by [typing.Annotated](https://docs.python.org/3/library/typing.html#typing.Annotated) function.
