### ISSUE TITLE
Initialize DeseqDataSet from existing AnnData object

### ISSUE THREAD

**Issue by grst** [owkin/PyDESeq2#94]
**Is your feature request related to a problem? Please describe.**
I have an existing AnnData object (e.g. with pseudobulk) and want to perform DE analysis 
using pydeseq2. While Pydeseq2 now extends AnnData, it is not clear to me what would be the recommended way to create a `DeseqDataSet` from an existing `AnnData` object. 

Example dataset:
```python
import scanpy as sc
import decoupler as dc

adata = sc.read("wu2020_3k.h5ad", backup_url="https://github.com/scverse/scirpy/releases/download/d0.1.0/wu2020_3k.h5ad")
pb = dc.get_pseudobulk(adata, sample_col="patient", groups_col="source")

# this looses additional information from AnnData and requires to specify X and obs directly
dds = DeseqDataSet(adata.X, adata.obs, ...)
```

**Describe the solution you'd like**
```python
# Either accept AnnData in the constructor
dds = DeseqDataSet(adata, ...)

# Or use a static method
dds = DeseqDataSet.from_anndata(adata, layer="raw_counts", use_raw=False)
```

CC @Zethson @ivirshup

**Comment by BorisMuzellec** [comment]
Hi, indeed this is part of our TODO list.

IMO the first option (accepting AnnData in the constructor) would be the most natural.
